server:
  port: 8002
spring:
  application:
    name: loveshopping-product-test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/loveshopping_product
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:org/pengxx/loveshopping/mapper/*Mapper.xml
  type-aliases-package: org.pengxx.loveshopping.domain,org.pengxx.loveshopping.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true #显示真实ip